require('./server/api/db/mongodb')
require('./server/api/data/data')
require('./server/api/data/validation')
require('./server/api/routes/data_add')
require('./server/api/routes/menu_add')
require('./server/api/routes/routes')
require('./server/client/routes')
