- hosts: homehub.cloud.test.hartcode.com
  remote_user: hartalex
  vars:
    commit: "{{ lookup('env', 'TRAVIS_COMMIT') }}"
    tag: "{{ lookup('env', 'TRAVIS_BRANCH') }}"
    api_url: "{{ lookup('env', 'API_URL') }}"
  tasks:
    - name: get container
      become: true
      command: 'gcloud docker -- pull gcr.io/hartonline-cloud/temperature_hub:{{tag}}-{{commit}}'
    - name: restart docker container
      become: true
      docker_container:
        name: 'temp_hub_{{tag}}'
        image: 'gcr.io/hartonline-cloud/temperature_hub:{{tag}}-{{commit}}'
        state: started
        restart: yes
        recreate: yes
        restart_policy: always
        ports:
          - '443:443'
          - '80:80'
        volumes:
          - '/home/hartalex/temp_hub/config.js:/root/temperature_hub/src/server/config.js'
          - '/home/hartalex/temp_hub/config2.js:/root/temperature_hub/src/config.js'
          - '/home/hartalex/temp_hub/logdir:/var/log'
          - '/etc/ssl:/etc/ssl'
        network_mode: host
        env:
          - "API_URL:{{api_url}}"
    - name: restart mongo
      become: true
      docker_container:
        name: 'mongo'
        image: 'mongo:latest'
        state: started
        restart: yes
        recreate: yes
        restart_policy: always
        ports:
          - '127.0.0.1:27017:27017'
        volumes:
          - '/home/hartalex/mongodb/datadir:/data/db'
        network_mode: host
    - wait_for: timeout=30
    - name: Get JSON from page
      uri: url="https://homehub.cloud.test.hartcode.com/info" return_content=yes
      register: json_response
    - name: Validate commit
      fail: msg="The commits don't match"
      when: "(json_response.content|from_json)['commit'] is defined and (json_response.content|from_json)['commit'] != commit"
